version: '2'
services:
  test-kafka-consumer:
    container_name: test-kafka-consumer
    build:
      context: .
    image: test-kafka-consumer:latest
    ports:
      - "8390:8080"
      - "8391:8081"
      - "8790:8787"
    restart: always
    environment:
      - KAFKA_CONSUMER_TEST_EVENT_TOPIC=test-event-topic
      - KAFKA_PRODUCER_TEST_ERROR_TOPIC=test-error-topic
      - KAFKA_SECURITY_PROTOCOL=PLAINTEXT
      - SECRET_KAFKA_USERNAME=
      - SECRET_KAFKA_PASSWORD=
      - KAFKA_BROKER_HOST_1=kafka-broker
      - KAFKA_BROKER_HOST-2=kafka-broker
      - KAFKA_BROKER_HOST_3=kafka-broker
      - KAFKA_BROKER_HOST_4=kafka-broker
      - KAFKA_BROKER_HOST_5=kafka-broker
      - KAFKA_BROKER_PORT=9092
      - KAFKA_SCHEMAREGISTRY_HOST=kafka-schema-registry
      - KAFKA_SCHEMAREGISTRY_PORT=8081


    networks:
     - sda
networks:
  sda:
    external:
      name: sda.net
